[app]
name = "keyauth"
host = "0.0.0.0"
http_port = "8050"
grpc_prot = "18050"
key  = "this is your app key"

[mongodb]
endpoints = ["xxx:xxx"]
username = "xxx"
password = "xxxx"
database = "keyauth"

[nats]
servers = ["nats://127.0.0.1:4222"]
user_name = ""
password = ""

[log]
level = "debug"
path = "logs"
format = "text"
to = "stdout"