[app]
name = "keyauth"
host = "0.0.0.0"
http_port = "8050"
grpc_prot = "18050"
key  = "this is your app key"

[mongodb]
endpoints = ["xxx:xxx"]
username = "xxx"
password = "xxxx"
database = "keyauth"

[mcenter]
adress="127.0.0.1:18010"
client_id=""
client_secret=""

[log]
level = "debug"
path = "logs"
format = "text"
to = "stdout"